### ISSUE TITLE
Hotjar is not found

### ISSUE THREAD

**Issue by janswist** [henk-badenhorst/vue-hotjar#14]
I have strange error - Hotjar is being detected on localhost when `isProduction: true`, but when I change it to `isProduction: process.env.NODE_ENV !== 'development'` it's no detected on the production site even though code appears in the source:
![image](https://user-images.githubusercontent.com/5583954/97763092-df01eb80-1b0a-11eb-88c0-d6c53512b207.png)

Can I ask for help in that regard?

Site in question: https://doctempleapp.com/?hjVerifyInstall=2070936

**Comment by henk-badenhorst** [comment]
Yes sure, From what I see the site you sent is tracking correctly. I can see HotJar on the window object `window.hj` and your code looks correct. I even get the verified toaster message when browsing to the URL you sent.

During development of this plugin I noticed that If you have AD Blockers / privacy related browser extensions installed or using a browser such as the [Brave browser](https://brave.com/) HotJar will not track. Although the script will appear in the source as you pointed out. Could this be your issue? Some privacy related browser extension allow cookies to be set on localhost.

**Comment by janswist** [comment]
Strangely it works for me now as well. Not sure what happened (maybe multi-region caching - and the region HotJar was getting it from was not yet updated?). I first noticed when despite not seeing verification toast I got recordings.

Thanks for the help!
