### ISSUE TITLE
Multiple different Hotjar scripts detected

### ISSUE THREAD

**Issue by iniakunhuda** [henk-badenhorst/vue-hotjar#18]
Hi!

Great plugin for hotjar in vue. But I have a problem, hotjar detect 2 scripts in my code. I just add one hotjar script from this plugin only. How can I solve this? Thank you

**Comment by henk-badenhorst** [comment]
Hi, Thanks for the feedback regarding the plugin. I have not seen this issue before can you please give me some more info to replicate this. 

- Vue version and configuration?
- How did you add the plugin?
- How did you establish that it is duplicated?
- Are you seeing this in production or local dev?
- If you seeing this in production what is the link?

The more information I have the better I could help you solve this. I don't think it is a bug in the plugin but let's not leave that to chance.

**Comment by iniakunhuda** [comment]
Hi!
The issue was solved. Maybe my browser has cache before so detecting multiple hotjar in vue. But now everything is ok
