### ISSUE TITLE
Tracking user data

### ISSUE THREAD

**Issue by t0milee** [henk-badenhorst/vue-hotjar#8]
How would I track user data using this lib, bellow is the example from the docs, not sure if it's supported via this lib?

```js
<!-- Install this snippet AFTER the Hotjar tracking code. -->
<script>
var userId = your_user_id || null; // Replace your_user_id with your own if available.
window.hj('identify', userId, {
    // Add your own custom attributes here. Some EXAMPLES:
    // 'Signed up': '2019—06-20Z', // Signup date in ISO-8601 format.
    // 'Last purchase category': 'Electronics', // Send strings with quotes around them.
    // 'Total purchases': 15, // Send numbers without quotes.
    // 'Last purchase date': '2019-06-20Z', // Send dates in ISO-8601 format.
    // 'Last refund date': null, // Send null when no value exists for a user.
});
</script>
```

**Comment by henk-badenhorst** [comment]
Hi @t0milee this is related to issue #7 where and enhancement is requested to add the `window.hj` object to the Vue Prototype which can be then accessed by `$hj` globally. I have closed this issue as it is a duplicate. However for now you have access to `window.hj` the Hotjar scripts adds that by default to the window object. You can perform your logic there as per the documentation. However if isProduction is set to `false` the `hj ` object will not be added to the window object. Please follow #7  for the enhancement. I will try and get this added as soon as possible. However there are some complexities I am working through, explained in #7.
